package skillgen_test

import (
	"encoding/json"
	"fmt"
	"path/filepath"
	"strings"
	"testing"

	"github.com/frodi-karlsson/jev-cli/internal/skillgen"
)

func TestRenderSkill(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name     string
		skill    skillgen.Skill
		intro    string
		sections []string
		source   string
		want     string
	}{
		{
			name:   "should emit yaml frontmatter carrying only the agent skills fields when only name and description are set",
			skill:  skillgen.Skill{Name: "my-skill", Description: "does a thing"},
			source: "skills/my-skill/skill.json",
			want: "---\n" +
				"# Code generated by jev skillgen from skills/my-skill/skill.json. DO NOT EDIT.\n" +
				"name: my-skill\n" +
				"description: does a thing\n" +
				"---\n",
		},
		{
			name: "should emit compatibility license and metadata when set",
			skill: skillgen.Skill{
				Name:          "jev-gate",
				Description:   "gate a command on jev",
				Compatibility: "Requires the jev binary on PATH.",
				License:       "MIT",
				Metadata:      map[string]string{"version": "0.1.0", "author": "team"},
			},
			source: "skills/jev-gate/skill.json",
			want: "---\n" +
				"# Code generated by jev skillgen from skills/jev-gate/skill.json. DO NOT EDIT.\n" +
				"name: jev-gate\n" +
				"description: gate a command on jev\n" +
				"compatibility: Requires the jev binary on PATH.\n" +
				"license: MIT\n" +
				"metadata:\n" +
				"  author: team\n" +
				"  version: 0.1.0\n" +
				"---\n",
		},
		{
			name: "should omit an optional field entirely rather than emit an empty value",
			skill: skillgen.Skill{
				Name:        "my-skill",
				Description: "does a thing",
				License:     "MIT",
			},
			source: "skills/my-skill/skill.json",
			want: "---\n" +
				"# Code generated by jev skillgen from skills/my-skill/skill.json. DO NOT EDIT.\n" +
				"name: my-skill\n" +
				"description: does a thing\n" +
				"license: MIT\n" +
				"---\n",
		},
		{
			name: "should emit the intro then every rule then the sections in order",
			skill: skillgen.Skill{
				Name:        "jev",
				Description: "desc",
				Rules: []skillgen.Rule{
					{ID: "r1", Short: "Do the thing.", Why: "Because reasons."},
					{ID: "r2", Short: "Do the other thing.", Why: "Because other reasons."},
				},
			},
			intro:    "This is the intro.",
			sections: []string{"## Section One\n\nContent one.", "## Section Two\n\nContent two."},
			source:   "skills/jev/skill.json",
			want: "---\n" +
				"# Code generated by jev skillgen from skills/jev/skill.json. DO NOT EDIT.\n" +
				"name: jev\n" +
				"description: desc\n" +
				"---" +
				"\n\n" +
				"This is the intro." +
				"\n\n" +
				"## Rules" +
				"\n\n" +
				"### Do the thing." +
				"\n\n" +
				"Because reasons." +
				"\n\n" +
				"### Do the other thing." +
				"\n\n" +
				"Because other reasons." +
				"\n\n" +
				"## Section One\n\nContent one." +
				"\n\n" +
				"## Section Two\n\nContent two." +
				"\n",
		},
		{
			name: "should render a rule with short as the heading why as prose and bad and good as two fenced blocks each labelled",
			skill: skillgen.Skill{
				Name:        "jev-gate",
				Description: "gate",
				Rules: []skillgen.Rule{
					{
						ID:    "drop-q",
						Short: "Drop -q when you use --assert.",
						Why:   "Because both gates cannot pass together.",
						Bad:   "jev 'x' -q --assert 'v < 0.5'",
						Good:  "jev 'x' --assert 'v < 0.5' >/dev/null",
					},
				},
			},
			source: "skills/jev-gate/skill.json",
			want: "---\n" +
				"# Code generated by jev skillgen from skills/jev-gate/skill.json. DO NOT EDIT.\n" +
				"name: jev-gate\n" +
				"description: gate\n" +
				"---" +
				"\n\n" +
				"## Rules" +
				"\n\n" +
				"### Drop -q when you use --assert." +
				"\n\n" +
				"Because both gates cannot pass together." +
				"\n\n" +
				"**Bad:**\n\n```sh\njev 'x' -q --assert 'v < 0.5'\n```" +
				"\n\n" +
				"**Good:**\n\n```sh\njev 'x' --assert 'v < 0.5' >/dev/null\n```" +
				"\n",
		},
		{
			name: "should omit the bad and good blocks when the rule has neither",
			skill: skillgen.Skill{
				Name:        "jev-gate",
				Description: "gate",
				Rules: []skillgen.Rule{
					{ID: "r1", Short: "Do the thing.", Why: "Because reasons."},
				},
			},
			source: "skills/jev-gate/skill.json",
			want: "---\n" +
				"# Code generated by jev skillgen from skills/jev-gate/skill.json. DO NOT EDIT.\n" +
				"name: jev-gate\n" +
				"description: gate\n" +
				"---" +
				"\n\n" +
				"## Rules" +
				"\n\n" +
				"### Do the thing." +
				"\n\n" +
				"Because reasons." +
				"\n",
		},
		{
			name: "should omit only the good block when the rule has bad but no good",
			skill: skillgen.Skill{
				Name:        "jev-gate",
				Description: "gate",
				Rules: []skillgen.Rule{
					{ID: "r1", Short: "Do the thing.", Why: "Because reasons.", Bad: "bad example"},
				},
			},
			source: "skills/jev-gate/skill.json",
			want: "---\n" +
				"# Code generated by jev skillgen from skills/jev-gate/skill.json. DO NOT EDIT.\n" +
				"name: jev-gate\n" +
				"description: gate\n" +
				"---" +
				"\n\n" +
				"## Rules" +
				"\n\n" +
				"### Do the thing." +
				"\n\n" +
				"Because reasons." +
				"\n\n" +
				"**Bad:**\n\n```sh\nbad example\n```" +
				"\n",
		},
		{
			name: "should omit only the bad block when the rule has good but no bad",
			skill: skillgen.Skill{
				Name:        "jev-gate",
				Description: "gate",
				Rules: []skillgen.Rule{
					{ID: "r1", Short: "Do the thing.", Why: "Because reasons.", Good: "good example"},
				},
			},
			source: "skills/jev-gate/skill.json",
			want: "---\n" +
				"# Code generated by jev skillgen from skills/jev-gate/skill.json. DO NOT EDIT.\n" +
				"name: jev-gate\n" +
				"description: gate\n" +
				"---" +
				"\n\n" +
				"## Rules" +
				"\n\n" +
				"### Do the thing." +
				"\n\n" +
				"Because reasons." +
				"\n\n" +
				"**Good:**\n\n```sh\ngood example\n```" +
				"\n",
		},
		{
			name:   "should start the file with a generated marker naming the source",
			skill:  skillgen.Skill{Name: "jev-stream", Description: "streams records"},
			source: "skills/jev-stream/skill.json",
			want: "---\n" +
				"# Code generated by jev skillgen from skills/jev-stream/skill.json. DO NOT EDIT.\n" +
				"name: jev-stream\n" +
				"description: streams records\n" +
				"---\n",
		},
		{
			name: "should link to references after the sections",
			skill: skillgen.Skill{
				Name:        "jev-gate",
				Description: "gate",
				References:  []string{"references/failures.md", "references/more.md"},
			},
			sections: []string{"## Section\n\nBody."},
			source:   "skills/jev-gate/skill.json",
			want: "---\n" +
				"# Code generated by jev skillgen from skills/jev-gate/skill.json. DO NOT EDIT.\n" +
				"name: jev-gate\n" +
				"description: gate\n" +
				"---" +
				"\n\n" +
				"## Section\n\nBody." +
				"\n\n" +
				"## References" +
				"\n\n" +
				"- [failures.md](references/failures.md)\n- [more.md](references/more.md)" +
				"\n",
		},
		{
			name:     "should preserve leading indentation in a section",
			skill:    skillgen.Skill{Name: "jev-gate", Description: "gate"},
			sections: []string{"    indented line one\n    indented line two"},
			source:   "skills/jev-gate/skill.json",
			want: "---\n" +
				"# Code generated by jev skillgen from skills/jev-gate/skill.json. DO NOT EDIT.\n" +
				"name: jev-gate\n" +
				"description: gate\n" +
				"---" +
				"\n\n" +
				"    indented line one\n    indented line two" +
				"\n",
		},
		{
			name:     "should normalize a crlf fragment to lf",
			skill:    skillgen.Skill{Name: "jev-gate", Description: "gate"},
			sections: []string{"Line one\r\nLine two"},
			source:   "skills/jev-gate/skill.json",
			want: "---\n" +
				"# Code generated by jev skillgen from skills/jev-gate/skill.json. DO NOT EDIT.\n" +
				"name: jev-gate\n" +
				"description: gate\n" +
				"---" +
				"\n\n" +
				"Line one\nLine two" +
				"\n",
		},
		{
			name:   "should normalize a windows separated source in the marker",
			skill:  skillgen.Skill{Name: "jev-gate", Description: "gate"},
			source: `skills\jev-gate\skill.json`,
			want: "---\n" +
				"# Code generated by jev skillgen from " + filepath.ToSlash(`skills\jev-gate\skill.json`) +
				". DO NOT EDIT.\n" +
				"name: jev-gate\n" +
				"description: gate\n" +
				"---\n",
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()

			got := skillgen.RenderSkill(tc.skill, tc.intro, tc.sections, tc.source)

			if string(got) != tc.want {
				t.Errorf("RenderSkill() =\n%q\nwant\n%q", got, tc.want)
			}
		})
	}
}

func TestRenderGemini(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name   string
		skill  skillgen.Skill
		source string
		want   string
	}{
		{
			name: "should emit a description and a prompt",
			skill: skillgen.Skill{
				Name:        "jev",
				Description: "the general skill",
				Rules: []skillgen.Rule{
					{ID: "r1", Short: "Batch every question into one call.", Why: "cheaper"},
				},
			},
			source: "skills/jev/skill.json",
			want: "# Code generated by jev skillgen from skills/jev/skill.json. DO NOT EDIT.\n\n" +
				`description = "the general skill"` + "\n" +
				`prompt = "1. Batch every question into one call."` + "\n",
		},
		{
			name: "should number every rule's short in order",
			skill: skillgen.Skill{
				Name:        "jev-gate",
				Description: "gate a command",
				Rules: []skillgen.Rule{
					{ID: "r1", Short: "First.", Why: "why one"},
					{ID: "r2", Short: "Second.", Why: "why two"},
					{ID: "r3", Short: "Third.", Why: "why three"},
				},
			},
			source: "skills/jev-gate/skill.json",
			want: "# Code generated by jev skillgen from skills/jev-gate/skill.json. DO NOT EDIT.\n\n" +
				`description = "gate a command"` + "\n" +
				`prompt = "1. First.\n2. Second.\n3. Third."` + "\n",
		},
		{
			name: "should include no why no bad and no good",
			skill: skillgen.Skill{
				Name:        "jev-gate",
				Description: "gate a command",
				Rules: []skillgen.Rule{
					{
						ID:    "r1",
						Short: "Drop -q when you use --assert.",
						Why:   "why this rule exists in full",
						Bad:   "the bad example command",
						Good:  "the good example command",
					},
				},
			},
			source: "skills/jev-gate/skill.json",
			want: "# Code generated by jev skillgen from skills/jev-gate/skill.json. DO NOT EDIT.\n\n" +
				`description = "gate a command"` + "\n" +
				`prompt = "1. Drop -q when you use --assert."` + "\n",
		},
		{
			name:   "should normalize a windows separated source in the marker",
			skill:  skillgen.Skill{Name: "jev-gate", Description: "gate a command"},
			source: `skills\jev-gate\skill.json`,
			want: "# Code generated by jev skillgen from " + filepath.ToSlash(`skills\jev-gate\skill.json`) +
				". DO NOT EDIT.\n\n" +
				`description = "gate a command"` + "\n" +
				`prompt = ""` + "\n",
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()

			got := skillgen.RenderGemini(tc.skill, tc.source)

			if string(got) != tc.want {
				t.Errorf("RenderGemini() =\n%q\nwant\n%q", got, tc.want)
			}
		})
	}

	t.Run("should escape a rule containing a quote so the toml parses", func(t *testing.T) {
		t.Parallel()

		skill := skillgen.Skill{
			Name:        "jev-gate",
			Description: "gate a command",
			Rules: []skillgen.Rule{
				{ID: "r1", Short: `Never write "unsafe" mode.`, Why: "why"},
			},
		}
		source := "skills/jev-gate/skill.json"

		want := "# Code generated by jev skillgen from skills/jev-gate/skill.json. DO NOT EDIT.\n\n" +
			`description = "gate a command"` + "\n" +
			`prompt = "1. Never write \"unsafe\" mode."` + "\n"

		got := skillgen.RenderGemini(skill, source)

		if string(got) != want {
			t.Fatalf("RenderGemini() =\n%q\nwant\n%q", got, want)
		}

		promptLine := findLine(t, string(got), "prompt = ")

		// go.mod carries no TOML parser and the task forbids adding one, but the TOML basic string
		// escapes used here, backslash, quote, newline, tab and carriage return, are the same
		// escapes JSON strings use, so decoding the quoted literal as JSON proves it round trips.
		var decoded string
		if err := json.Unmarshal([]byte(promptLine), &decoded); err != nil {
			t.Fatalf("prompt literal %q does not decode as a quoted string: %v", promptLine, err)
		}

		if want := `1. Never write "unsafe" mode.`; decoded != want {
			t.Errorf("decoded prompt = %q, want %q", decoded, want)
		}
	})

	t.Run("should escape a control character in a rule so the toml parses", func(t *testing.T) {
		t.Parallel()

		skill := skillgen.Skill{
			Name:        "jev-gate",
			Description: "gate a command",
			Rules: []skillgen.Rule{
				{ID: "r1", Short: "Reject a \x01\x08\x0c\x7f control byte.", Why: "why"},
			},
		}
		source := "skills/jev-gate/skill.json"

		soh := fmt.Sprintf(`\u%04X`, 0x01)
		del := fmt.Sprintf(`\u%04X`, 0x7f)

		want := "# Code generated by jev skillgen from skills/jev-gate/skill.json. DO NOT EDIT.\n\n" +
			`description = "gate a command"` + "\n" +
			`prompt = "1. Reject a ` + soh + `\b\f` + del + ` control byte."` + "\n"

		got := skillgen.RenderGemini(skill, source)

		if string(got) != want {
			t.Fatalf("RenderGemini() =\n%q\nwant\n%q", got, want)
		}

		promptLine := findLine(t, string(got), "prompt = ")

		// encoding/json rejects a raw control byte in a string, so this only decodes if SOH, DEL,
		// backspace and form feed were all actually escaped rather than passed through raw.
		var decoded string
		if err := json.Unmarshal([]byte(promptLine), &decoded); err != nil {
			t.Fatalf("prompt literal %q does not decode as a quoted string: %v", promptLine, err)
		}

		if want := "1. Reject a \x01\x08\x0c\x7f control byte."; decoded != want {
			t.Errorf("decoded prompt = %q, want %q", decoded, want)
		}
	})

	t.Run("should escape a tab in a rule so the toml parses", func(t *testing.T) {
		t.Parallel()

		skill := skillgen.Skill{
			Name:        "jev-gate",
			Description: "gate a command",
			Rules: []skillgen.Rule{
				{ID: "r1", Short: "Reject a\ttabbed byte.", Why: "why"},
			},
		}
		source := "skills/jev-gate/skill.json"

		want := "# Code generated by jev skillgen from skills/jev-gate/skill.json. DO NOT EDIT.\n\n" +
			`description = "gate a command"` + "\n" +
			`prompt = "1. Reject a\ttabbed byte."` + "\n"

		got := skillgen.RenderGemini(skill, source)

		if string(got) != want {
			t.Fatalf("RenderGemini() =\n%q\nwant\n%q", got, want)
		}

		promptLine := findLine(t, string(got), "prompt = ")

		var decoded string
		if err := json.Unmarshal([]byte(promptLine), &decoded); err != nil {
			t.Fatalf("prompt literal %q does not decode as a quoted string: %v", promptLine, err)
		}

		if want := "1. Reject a\ttabbed byte."; decoded != want {
			t.Errorf("decoded prompt = %q, want %q", decoded, want)
		}
	})
}

func findLine(t *testing.T, text, prefix string) string {
	t.Helper()

	for _, line := range strings.Split(text, "\n") {
		if after, ok := strings.CutPrefix(line, prefix); ok {
			return after
		}
	}

	t.Fatalf("no line starting with %q in %q", prefix, text)

	return ""
}
