package skillgen

import (
	"fmt"
	"path"
	"path/filepath"
	"sort"
	"strings"

	"github.com/goccy/go-yaml"
)

const generatedMarker = "Code generated by jev skillgen from %s. DO NOT EDIT."

// RenderSkill renders the portable SKILL.md body for skill, per spec section 3. intro and sections
// are the named fragments' contents in skill's order, and source is recorded in the generated marker.
func RenderSkill(skill Skill, intro string, sections []string, source string) []byte {
	blocks := []string{frontMatterBlock(skill, source), intro}

	if len(skill.Rules) > 0 {
		blocks = append(blocks, "## Rules")

		for _, rule := range skill.Rules {
			blocks = append(blocks, ruleBlocks(rule)...)
		}
	}

	blocks = append(blocks, sections...)

	if len(skill.References) > 0 {
		blocks = append(blocks, referencesBlock(skill.References))
	}

	return joinBlocks(blocks)
}

func frontMatterBlock(skill Skill, source string) string {
	fields := yaml.MapSlice{
		{Key: "name", Value: skill.Name},
		{Key: "description", Value: skill.Description},
	}

	if skill.Compatibility != "" {
		fields = append(fields, yaml.MapItem{Key: "compatibility", Value: skill.Compatibility})
	}

	if skill.License != "" {
		fields = append(fields, yaml.MapItem{Key: "license", Value: skill.License})
	}

	if len(skill.Metadata) > 0 {
		fields = append(fields, yaml.MapItem{Key: "metadata", Value: sortedMetadata(skill.Metadata)})
	}

	out, err := yaml.Marshal(fields)
	if err != nil {
		// Every field above is a string or a map of strings, so goccy/go-yaml cannot fail here.
		panic(err)
	}

	return "---\n# " + markerSentence(source) + "\n" + string(out) + "---"
}

func sortedMetadata(metadata map[string]string) yaml.MapSlice {
	keys := make([]string, 0, len(metadata))
	for key := range metadata {
		keys = append(keys, key)
	}

	sort.Strings(keys)

	fields := make(yaml.MapSlice, 0, len(keys))
	for _, key := range keys {
		fields = append(fields, yaml.MapItem{Key: key, Value: metadata[key]})
	}

	return fields
}

func ruleBlocks(rule Rule) []string {
	blocks := []string{"### " + rule.Short, rule.Why}

	if rule.Bad != "" {
		blocks = append(blocks, "**Bad:**\n\n```sh\n"+rule.Bad+"\n```")
	}

	if rule.Good != "" {
		blocks = append(blocks, "**Good:**\n\n```sh\n"+rule.Good+"\n```")
	}

	return blocks
}

func referencesBlock(references []string) string {
	lines := make([]string, len(references))
	for i, reference := range references {
		lines[i] = "- [" + path.Base(reference) + "](" + reference + ")"
	}

	return "## References\n\n" + strings.Join(lines, "\n")
}

func joinBlocks(blocks []string) []byte {
	nonEmpty := make([]string, 0, len(blocks))

	for _, block := range blocks {
		block = strings.ReplaceAll(block, "\r\n", "\n")
		block = strings.Trim(block, "\n")

		if block != "" {
			nonEmpty = append(nonEmpty, block)
		}
	}

	return []byte(strings.Join(nonEmpty, "\n\n") + "\n")
}

// RenderGemini renders the Gemini CLI custom command for skill, per spec section 3, a condensed
// restatement carrying the description and every rule's short, numbered in order.
func RenderGemini(skill Skill, source string) []byte {
	var out strings.Builder

	fmt.Fprintf(&out, "# %s\n\n", markerSentence(source))
	fmt.Fprintf(&out, "description = %s\n", quoteTOML(skill.Description))
	fmt.Fprintf(&out, "prompt = %s\n", quoteTOML(geminiPrompt(skill.Rules)))

	return []byte(out.String())
}

func markerSentence(source string) string {
	return fmt.Sprintf(generatedMarker, filepath.ToSlash(source))
}

func geminiPrompt(rules []Rule) string {
	lines := make([]string, len(rules))
	for i, rule := range rules {
		lines[i] = fmt.Sprintf("%d. %s", i+1, rule.Short)
	}

	return strings.Join(lines, "\n")
}

func quoteTOML(s string) string {
	var b strings.Builder

	b.WriteByte('"')

	for _, r := range s {
		switch r {
		case '\\':
			b.WriteString(`\\`)
		case '"':
			b.WriteString(`\"`)
		case '\n':
			b.WriteString(`\n`)
		case '\r':
			b.WriteString(`\r`)
		case '\b':
			b.WriteString(`\b`)
		case '\f':
			b.WriteString(`\f`)
		case '\t':
			b.WriteString(`\t`)
		default:
			if r < 0x20 || r == 0x7f {
				fmt.Fprintf(&b, `\u%04X`, r)
			} else {
				b.WriteRune(r)
			}
		}
	}

	b.WriteByte('"')

	return b.String()
}
