// Package formula renders the Homebrew formula for a onesie release from the release's checksums.
package formula

import (
	"bufio"
	"bytes"
	"fmt"
	"io"
	"regexp"
	"strings"
	"text/template"
)

const (
	releaseURL = "https://github.com/frodi-karlsson/onesie/releases/download"

	formulaSource = `# typed: false
# frozen_string_literal: true

# Generated by cmd/formulagen in frodi-karlsson/onesie. Do not edit it by hand.
class Onesie < Formula
  desc "Command line interface for TypeSafe Jev"
  homepage "https://github.com/frodi-karlsson/onesie"
  version "{{ .Version }}"
  license "MIT"

  on_macos do
    on_arm do
      url "{{ .Archives.darwin_arm64.URL }}"
      sha256 "{{ .Archives.darwin_arm64.SHA256 }}"
    end
    on_intel do
      url "{{ .Archives.darwin_amd64.URL }}"
      sha256 "{{ .Archives.darwin_amd64.SHA256 }}"
    end
  end

  on_linux do
    on_arm do
      url "{{ .Archives.linux_arm64.URL }}"
      sha256 "{{ .Archives.linux_arm64.SHA256 }}"
    end
    on_intel do
      url "{{ .Archives.linux_amd64.URL }}"
      sha256 "{{ .Archives.linux_amd64.SHA256 }}"
    end
  end

  def install
    bin.install "onesie"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/onesie version")
  end
end
`
)

var (
	versionPattern = regexp.MustCompile(`^[0-9A-Za-z][0-9A-Za-z.+-]*$`)
	sha256Pattern  = regexp.MustCompile(`^[0-9a-f]{64}$`)

	targets = []target{
		{os: "darwin", arch: "arm64"},
		{os: "darwin", arch: "amd64"},
		{os: "linux", arch: "arm64"},
		{os: "linux", arch: "amd64"},
	}

	formulaTemplate = template.Must(template.New("formula").Parse(formulaSource))
)

// Render returns the formula for version, a release version with or without its leading v, taking
// each archive's sha256 from checksums, the contents of the release's checksums.txt.
func Render(version string, checksums io.Reader) ([]byte, error) {
	version = strings.TrimPrefix(version, "v")
	if !versionPattern.MatchString(version) {
		return nil, fmt.Errorf("formula: %q is not a release version", version)
	}

	sums, err := parseChecksums(checksums)
	if err != nil {
		return nil, err
	}

	archives := make(map[string]archive, len(targets))

	for _, t := range targets {
		name := fmt.Sprintf("onesie_%s_%s_%s.tar.gz", version, t.os, t.arch)

		sum, ok := sums[name]
		if !ok {
			return nil, fmt.Errorf("formula: checksums.txt has no entry for %s", name)
		}

		archives[t.os+"_"+t.arch] = archive{
			URL:    fmt.Sprintf("%s/v%s/%s", releaseURL, version, name),
			SHA256: sum,
		}
	}

	var out bytes.Buffer
	if err := formulaTemplate.Execute(&out, formulaData{Version: version, Archives: archives}); err != nil {
		return nil, fmt.Errorf("formula: %w", err)
	}

	return out.Bytes(), nil
}

type target struct {
	os   string
	arch string
}

type archive struct {
	URL    string
	SHA256 string
}

type formulaData struct {
	Version  string
	Archives map[string]archive
}

func parseChecksums(r io.Reader) (map[string]string, error) {
	sums := make(map[string]string)
	scanner := bufio.NewScanner(r)

	for line := 1; scanner.Scan(); line++ {
		text := strings.TrimSpace(scanner.Text())
		if text == "" {
			continue
		}

		fields := strings.Fields(text)
		if len(fields) != 2 || !sha256Pattern.MatchString(fields[0]) {
			return nil, fmt.Errorf("formula: checksums.txt line %d is not a sha256 and a file name", line)
		}

		sums[strings.TrimPrefix(fields[1], "*")] = fields[0]
	}

	if err := scanner.Err(); err != nil {
		return nil, fmt.Errorf("formula: reading checksums.txt: %w", err)
	}

	return sums, nil
}
