package qfile

import (
	"bytes"
	"encoding/json"
	"slices"

	"github.com/frodi-karlsson/onesie/internal/limits"
	"github.com/frodi-karlsson/onesie/internal/plan"
)

// Schema returns the JSON Schema, draft 07, that describes a question file. A document with a top
// level questions key is a request body, and the schema accepts any of those.
func Schema() []byte {
	encoded, err := json.MarshalIndent(questionFileSchema(), "", "  ")
	if err != nil {
		// Every value in the schema is built here from strings, numbers and booleans.
		panic("onesie: encoding the question file schema: " + err.Error())
	}

	return append(encoded, '\n')
}

func questionFileSchema() node {
	gates := []string{"assert", "abstain_if", "$schema"}

	return node{
		Schema: "http://json-schema.org/draft-07/schema#",
		Title:  "onesie question file",
		Comment: "Generated by onesie. Each top level key is a question id, apart from assert, abstain_if " +
			"and $schema. The schema accepts any file some command line can use, so a rule a flag can " +
			"satisfy is left to onesie.",
		Type: "object",
		If:   &node{Required: []string{"questions"}},
		Then: true,
		Else: &node{
			PropertyNames: &node{
				Not: &node{AnyOf: []any{
					node{Enum: reservedIDs(gates)},
					node{Pattern: "^__", PatternErrorMessage: "An id that starts with two underscores is reserved."},
				}},
				ErrorMessage: "This question id is reserved.",
			},
			Properties: properties{
				{name: "assert", schema: node{Type: "string", Description: "A gate over every answer, as --assert takes it."}},
				{name: "abstain_if", schema: node{Type: "string", Description: "An abstain expression, as --abstain-if takes it."}},
				{name: "$schema", schema: node{Type: "string", Description: "The schema an editor checks this file against. onesie ignores it."}},
			},
			AdditionalProperties: node{Ref: "#/definitions/question"},
		},
		Definitions: properties{
			{name: "question", schema: questionSchema()},
			{name: "fields", schema: fieldsSchema()},
			{name: "pick", schema: pickSchema()},
			{name: "rate", schema: rateSchema()},
		},
	}
}

func reservedIDs(gates []string) []string {
	ids := []string{plan.PositionalID}

	for _, id := range plan.ReservedIDs() {
		if !slices.Contains(gates, id) {
			ids = append(ids, id)
		}
	}

	return ids
}

func questionSchema() node {
	return node{
		Description: "A question, as its instructions alone or as a mapping of its fields.",
		AnyOf: []any{
			node{Type: "string"},
			node{Ref: "#/definitions/fields"},
		},
	}
}

func fieldsSchema() node {
	rubric := []string{"yes_means", "no_means", "true", "false"}
	shaped := node{AnyOf: []any{required("pick"), required("rate")}}

	return node{
		Type:                 "object",
		Required:             []string{"ask"},
		AdditionalProperties: false,
		Properties: properties{
			{name: "ask", schema: node{Description: "The instructions sent to the API."}},
			{name: "yes_means", schema: node{Description: "What a yes means."}},
			{name: "no_means", schema: node{Description: "What a no means."}},
			{name: "true", schema: node{Description: "Another spelling of yes_means."}},
			{name: "false", schema: node{Description: "Another spelling of no_means."}},
			{name: "pick", schema: described("The options, as a sequence of names or a mapping of name to description.", "#/definitions/pick")},
			{name: "rate", schema: described("The levels from lowest to highest, as names, one key mappings of name "+
				"to description, or a mapping of name to description.", "#/definitions/rate")},
			{name: "threshold", schema: node{
				Type:        "number",
				Description: "The yes probability a yes/no answer must reach, between 0 and 1.",
			}},
			{name: "min_confidence", schema: node{
				Type:        "number",
				Description: "The confidence a pick or rate answer must reach, between 0 and 1, or the fallback stands in.",
			}},
			{name: "fallback", schema: node{
				Type:        []string{"string", "boolean"},
				Description: "The answer that stands in for one that falls short.",
			}},
		},
		AllOf: []any{
			node{
				Not:          &node{Required: []string{"pick", "rate"}},
				ErrorMessage: "A question has pick or rate, not both.",
			},
			node{
				If: &shaped,
				Then: &node{
					Not:          &node{AnyOf: append(requiredEach(rubric...), required("threshold"))},
					ErrorMessage: "A pick or rate question takes no yes_means, no_means, true, false or threshold.",
				},
				Else: &node{
					Properties: properties{
						{name: "fallback", schema: node{
							Description: "A yes/no question falls back to true, false, yes or no.",
							Examples:    []any{true, false, "yes", "no"},
						}},
					},
				},
			},
		},
	}
}

func described(description, ref string) node {
	return node{Description: description, AllOf: []any{node{Ref: ref}}}
}

func pickSchema() node {
	return node{
		OneOf: []any{
			node{
				Type:        "array",
				Items:       &node{Type: "string"},
				UniqueItems: true,
				MaxItems:    new(limits.MaxChoiceOptions),
			},
			node{
				Type:          "object",
				MaxProperties: new(limits.MaxChoiceOptions),
			},
		},
	}
}

func rateSchema() node {
	return node{
		OneOf: []any{
			node{
				Type:        "array",
				Items:       &node{AnyOf: []any{node{Type: "string"}, level()}},
				UniqueItems: true,
				MaxItems:    new(limits.MaxScoreLevels),
			},
			node{
				Type:          "object",
				MaxProperties: new(limits.MaxScoreLevels),
			},
		},
	}
}

func level() node {
	return node{Type: "object", MinProperties: new(1), MaxProperties: new(1)}
}

func required(key string) node {
	return node{Required: []string{key}}
}

func requiredEach(keys ...string) []any {
	each := make([]any, 0, len(keys))
	for _, key := range keys {
		each = append(each, required(key))
	}

	return each
}

type node struct {
	Schema               string     `json:"$schema,omitempty"`
	Title                string     `json:"title,omitempty"`
	Comment              string     `json:"$comment,omitempty"`
	Description          string     `json:"description,omitempty"`
	Ref                  string     `json:"$ref,omitempty"`
	Type                 any        `json:"type,omitempty"`
	Enum                 []string   `json:"enum,omitempty"`
	Pattern              string     `json:"pattern,omitempty"`
	PatternErrorMessage  string     `json:"patternErrorMessage,omitempty"`
	Examples             []any      `json:"examples,omitempty"`
	Minimum              *float64   `json:"minimum,omitempty"`
	Maximum              *float64   `json:"maximum,omitempty"`
	Required             []string   `json:"required,omitempty"`
	PropertyNames        *node      `json:"propertyNames,omitempty"`
	Properties           properties `json:"properties,omitempty"`
	AdditionalProperties any        `json:"additionalProperties,omitempty"`
	MinProperties        *int       `json:"minProperties,omitempty"`
	MaxProperties        *int       `json:"maxProperties,omitempty"`
	Dependencies         properties `json:"dependencies,omitempty"`
	Items                *node      `json:"items,omitempty"`
	UniqueItems          bool       `json:"uniqueItems,omitempty"`
	MinItems             *int       `json:"minItems,omitempty"`
	MaxItems             *int       `json:"maxItems,omitempty"`
	AllOf                []any      `json:"allOf,omitempty"`
	AnyOf                []any      `json:"anyOf,omitempty"`
	OneOf                []any      `json:"oneOf,omitempty"`
	Not                  *node      `json:"not,omitempty"`
	ErrorMessage         string     `json:"errorMessage,omitempty"`
	If                   *node      `json:"if,omitempty"`
	Then                 any        `json:"then,omitempty"`
	Else                 any        `json:"else,omitempty"`
	Definitions          properties `json:"definitions,omitempty"`
}

type properties []property

type property struct {
	name   string
	schema any
}

func (p properties) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer

	buf.WriteByte('{')

	for i, item := range p {
		if i > 0 {
			buf.WriteByte(',')
		}

		name, err := json.Marshal(item.name)
		if err != nil {
			return nil, err
		}

		value, err := json.Marshal(item.schema)
		if err != nil {
			return nil, err
		}

		buf.Write(name)
		buf.WriteByte(':')
		buf.Write(value)
	}

	buf.WriteByte('}')

	return buf.Bytes(), nil
}
