# typed: false
# frozen_string_literal: true

# Generated by cmd/formulagen in frodi-karlsson/onesie. Do not edit it by hand.
class Onesie < Formula
  desc "Command line interface for TypeSafe Jev"
  homepage "https://github.com/frodi-karlsson/onesie"
  version "1.2.3"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/frodi-karlsson/onesie/releases/download/v1.2.3/onesie_1.2.3_darwin_arm64.tar.gz"
      sha256 "d56e8ada9afde9bdfec0b1d489c0ed5f8631cc37c94f2640fd4a7df0f3b9aa5e"
    end
    on_intel do
      url "https://github.com/frodi-karlsson/onesie/releases/download/v1.2.3/onesie_1.2.3_darwin_amd64.tar.gz"
      sha256 "c8a18e68909506d06a6275fb3d96ce0702167e6bf2f75802bdb95d9118101fcb"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/frodi-karlsson/onesie/releases/download/v1.2.3/onesie_1.2.3_linux_arm64.tar.gz"
      sha256 "605866563c3a5fd6b117cac40fdad4664fcca3faa0b2475480a9a92244735842"
    end
    on_intel do
      url "https://github.com/frodi-karlsson/onesie/releases/download/v1.2.3/onesie_1.2.3_linux_amd64.tar.gz"
      sha256 "840e174a0f5ce5d3bf7965c8ff434184fcf7d3838071fb128ccf649700f76047"
    end
  end

  def install
    bin.install "onesie"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/onesie version")
  end
end
